Toggle nav
VICTOR-CHUKWU/portfolio pull request #13
Opened 2021-09-06 13:18 UTC by VICTOR-CHUKWU

working on sidebar toggle display

2021-09-06 13:46 UTC, carlos-ssh requested changes
Hi @VICTOR-CHUKWU , 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-06 13:46 UTC, carlos-ssh commented on index.js
> +// anchorLink.forEach((anchor)=> anchor.addEventListener('click', closeSideBar))
Your linter for JS it's missing in your project you can find it [here](https://github.com/microverseinc/linters-config/tree/master/javascript).
- kindly add ESLint into your PR

[OPTIONAL]
Keep your project clean and professional.
- Remove commented code.

2021-09-06 13:46 UTC, carlos-ssh commented on style.css
Provide the requested style in your Figma template:
![Screen Shot 2021-09-06 at 8 45 05](https://user-images.githubusercontent.com/22258274/132226729-aab323ce-9fcb-435e-b509-04718427cc5c.png)

This is your design: 
![Screen Shot 2021-09-06 at 8 44 33](https://user-images.githubusercontent.com/22258274/132226799-a62662cb-29d6-4e24-bff9-cf2019505bdf.png)

2021-09-06 16:45 UTC, od-c0d3r requested changes
Hi @VICTOR-CHUKWU , @KayLemba 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

Please use the right Github workflow referenced by the previous reviewer.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-09-06 16:47 UTC, od-c0d3r commented on index.js
> +// anchorLink.forEach((anchor)=> anchor.addEventListener('click', closeSideBar))
The requested change is not fulfilled.

Please change your current workflow folder with the one referenced by the previous reviewer.
So that Github workflows could run their own linters on your pull request. 👍🏼

2021-09-07 07:28 UTC, addod19 approved these changes
## Hi @VICTOR-CHUKWU, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

### Optional comments are a way of helping us learn and make our project even better

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
__Happy coding__ :man_technologist: 
[Daniel Larbi Addo](https://www.linkedin.com/in/daniel-larbi-addo/)

2021-09-07 07:28 UTC, addod19 commented on .eslintrc.json
> +{
### Optional
It would be better if we improve our PR, we can provide a little information based on the project description. For example;
```
In this project, I implemented the following
- [ ] This is the first project in which students should set up both JavaScript and HTML&CSS linters in the project repository.
- [ ] On desktop size the hamburger menu button is not visible.
- [ ] On mobile the hamburger menu button is visible.
- [ ] When the user clicks (or taps) the hamburger button, the mobile menu appears.
- [ ] When the user clicks (or taps) the close (X) button, the mobile menu disappear.
- [ ] When the user clicks (or taps) any of the mobile menu options, a correct part of the page is displayed.
- [ ] When the user clicks (or taps) any option of the mobile menu, the mobile menu disappear.
- [ ] The hamburger button and menu follows the design from the chosen template in Figma (e.g., font, colors, images, tests, margins).
- [ ] The JavaScript code is implemented following the best practices.
```

2021-09-07 07:28 UTC, addod19 commented on .github/workflows/linters.yml
>            [ -f .hintrc ] || wget https://raw.githubusercontent.com/microverseinc/linters-config/master/html-css/.hintrc
### Optional
- [ ] It would be better if we capitalize our commit messages going forward, this makes our repo professional

2021-09-07 07:41 UTC, merged