first commit on desktop view
VICTOR-CHUKWU/portfolio pull request #5
Opened 2021-08-19 10:13 UTC by VICTOR-CHUKWU

design and styling of the desktop view

2021-08-19 10:18 UTC, mke2111 requested changes
### Hey @VICTOR-CHUKWU, 

**This is a great project you have going on, well-done lad**. 
   
**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

## Required Changes ♻️
_Check the inline comments under the review for sections to improve._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-19 10:20 UTC, mke2111 commented on style.css
> +@media all and (min-width: 769px) {
- [ ] The value for min-width property should be in range of 992px - 1100px. These are the accepted desktop screen breakpoints. Change your value. What you are using lies under the tablet screen breakpoints.

2021-08-19 10:25 UTC, mke2111 commented on style.css
> +  .hr {
- [ ] Add a little padding/margin between the line and the My recent works.
![Screenshot from 2021-08-19 13-24-25](https://user-images.githubusercontent.com/65501535/130053119-67781201-71b9-4ee1-a814-4845fb5c5c9e.png)

Original
![Screenshot from 2021-08-19 13-25-12](https://user-images.githubusercontent.com/65501535/130053240-c4da0c9f-5e25-47df-aec7-f5433e1b748a.png)

2021-08-19 10:28 UTC, mke2111 commented on style.css
> +  .projects {
- [ ] Align these two columns to the top.
![Screenshot from 2021-08-19 13-27-57](https://user-images.githubusercontent.com/65501535/130053582-1b02eeef-76f3-4062-8670-51b74be876d2.png)

2021-08-19 10:34 UTC, mke2111 commented on style.css
> +  .about-me-inner {
- [ ] Let us match the padding/margin on the sides for the horizontal line to match the other sections.


Original
![Screenshot from 2021-08-19 13-31-29](https://user-images.githubusercontent.com/65501535/130054087-121a9a99-de88-491e-b8ab-284ccaa3745c.png)

2021-08-19 10:37 UTC, mke2111 commented on style.css
> +  .technologies {
- [ ] Align the technologies to the left for this section
![Screenshot from 2021-08-19 13-36-40](https://user-images.githubusercontent.com/65501535/130054770-2d8a3c75-c33d-47aa-90f8-9be99e1f12e6.png)

Original
![Screenshot from 2021-08-19 13-37-25](https://user-images.githubusercontent.com/65501535/130054865-9f923dce-e827-41ac-8888-d291f4bcd1aa.png)

2021-08-19 10:40 UTC, mke2111 commented on style.css
> +  .grid-desktop form {
- [ ] Match the text for these sections.
![Screenshot from 2021-08-19 13-39-20](https://user-images.githubusercontent.com/65501535/130055097-cbf405cc-7ccf-4949-8027-e27eb6b7ebea.png)


Original
![Screenshot from 2021-08-19 13-40-10](https://user-images.githubusercontent.com/65501535/130055246-86f8e094-2e1e-40b4-84e4-4e21da145d38.png)

2021-08-19 10:43 UTC, mke2111 commented on style.css
> +
- [ ] Match this footer section

![Screenshot from 2021-08-19 13-42-19](https://user-images.githubusercontent.com/65501535/130055510-2cd632d2-f224-4303-80dd-fadbc0736fb8.png)

Original
![Screenshot from 2021-08-19 13-42-59](https://user-images.githubusercontent.com/65501535/130055593-bf72dbe6-4c2a-4fc6-875a-a43c54448472.png)

2021-08-19 11:12 UTC, VICTOR-CHUKWU commented on style.css
> +@media all and (min-width: 769px) {
hello, thanks for the review but wont it look messy in tablet..i actually gave a media query for desktop where needed below media break point of min-width: 769..kindly check it out

2021-08-19 11:18 UTC, mke2111 commented on style.css
> +@media all and (min-width: 769px) {
This milestone mainly focuses on the desktop version. So for all screen sizes below 992px should be considered mobile screens.

2021-08-20 05:13 UTC, Murodjon000 requested changes
**Hi Victor Chukwu 👋,** 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-08-20 05:13 UTC, Murodjon000 commented on style.css
> +  .technologies {
- [ ] Kindly make sure `technologies` are aligned to the left side properly, as the first reviewer mentioned.
- Try to make it the same as the Figma design.
![](https://user-images.githubusercontent.com/65501535/130054865-9f923dce-e827-41ac-8888-d291f4bcd1aa.png)

2021-08-20 05:13 UTC, Murodjon000 commented on style.css
> +  margin: 0 0.4rem;
- [ ] Please align the `li` in the centre. Because your `message` icon is not aligned in the centre. 
![](https://res.cloudinary.com/dflkwvvnz/image/upload/v1629436162/scrnli_8_20_2021_10-06-56_AM_vxwb39.png)

2021-08-20 05:13 UTC, Murodjon000 commented on style.css
> +  .grid-desktop form {
- [ ] It would be better if you change the form wrapper background colour to white in order to make your design the same as the Figma one.

2021-08-20 09:35 UTC, Emmyn5600 approved these changes
Hi, 
Good job so far! 👏🏼 @VICTOR-CHUKWU  

May I highlight the following:

- The repo looks professional.:heavy_check_mark:
- Git/GitHub flow best practices have been followed, however use a descriptive feature branch:heavy_check_mark:
- There are no linter errors:heavy_check_mark:
- You have descriptive PR:heavy_check_mark:
- Your project looks awesome:heavy_check_mark:

## STATUS: APPROVED :muscle::clap:

Congratulations! :tada:
Your project is complete!  It's time to merge it :shipit:
Great work on implementing the changes requested by the previous TSEs
 
 #### Optional suggestions but I highly recommend you to work on it before you merge
 
 - The technologies used (HTML, CSS and JavaScript) shouldn't be a link, it should be wrapped in the `ul li tag`
 - The `see project` button should have hover color and should be pointer, add `cursor: pointer` in the css class. 
  - Please check the comment under the review
  
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-08-20 09:35 UTC, Emmyn5600 commented on README.md
Optional suggestion

- [ ] Kindly fix the screenshot image you added.

2021-08-20 09:35 UTC, Emmyn5600 commented on README.md
> +
- [ ] Kindly, update your live link demo, seem to be different with the changes you did.

2021-08-20 09:35 UTC, Emmyn5600 commented on style.css
> +  margin: 0 0.4rem;
Well solved

2021-08-20 09:35 UTC, Emmyn5600 commented on style.css
> +  .hr {
Well done

2021-08-20 09:35 UTC, Emmyn5600 commented on style.css
> +  .projects {
Well done

2021-08-20 09:35 UTC, Emmyn5600 commented on style.css
> +  .grid-desktop form {
Well solved

2021-08-20 09:35 UTC, Emmyn5600 commented on style.css
> +
Well done

2021-08-20 09:35 UTC, Emmyn5600 commented on style.css
>  }
Optional suggestions

- [ ] Kindly add `overflow-x: hidden` to prevent scroll left for the page.

2021-08-20 09:45 UTC, merged